config/routes.rb
Rails.application.routes.draw do
  resources :page_designs
 root 'home#index'
 devise_for :users, controllers: { sessions: "users/sessions" ,registrations: "users/registrations",passwords: "users/passwords"}
end

app/models/page_design.rb
class PageDesign < ActiveRecord::Base
belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :page_design
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  	 @page_design = current_user.page_design
  	else
  	  @page_design = ""
  	end
  end
end

app/controllers/page_designs_controller.rb
class PageDesignsController < ApplicationController
  before_action :set_page_design, only: [:show, :edit, :update, :destroy]

  # GET /page_designs
  # GET /page_designs.json
  def index
    @page_design = current_user.page_design

  end

  # GET /page_designs/1
  # GET /page_designs/1.json
  def show
  end

  # GET /page_designs/new
  def new
    @page_design = PageDesign.new
  end

  # GET /page_designs/1/edit
  def edit
  end

  # POST /page_designs
  # POST /page_designs.json
  def create
    @page_design = PageDesign.new(page_design_params)
    @page_design.user_id = current_user.id
    respond_to do |format|
      if @page_design.save
        format.html { redirect_to @page_design, notice: 'Page design was successfully created.' }
        format.json { render :show, status: :created, location: @page_design }
      else
        format.html { render :new }
        format.json { render json: @page_design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_designs/1
  # PATCH/PUT /page_designs/1.json
  def update
    respond_to do |format|
      if @page_design.update(page_design_params)
        format.html { redirect_to @page_design, notice: 'Page design was successfully updated.' }
        format.json { render :show, status: :ok, location: @page_design }
      else
        format.html { render :edit }
        format.json { render json: @page_design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_designs/1
  # DELETE /page_designs/1.json
  def destroy
    @page_design.destroy
    respond_to do |format|
      format.html { redirect_to page_designs_url, notice: 'Page design was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_design
      @page_design = PageDesign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_design_params
      params.require(:page_design).permit(:page_title, :page_font,:header_bg_color,:body_bg_color,:about_bg_color,:services_bg_color,:portfolio_bg_color,:footer_bg_color)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/page_designs_helper.rb
module PageDesignsHelper
end

app/views/home/index.html.erb
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>About Travel Tripper</h1>
                <hr>
                <p>Your strategic partner in hotel distribution and e-commerce.</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Who we are</h2>
                    <hr class="light">
                    <p class="text-faded">Travel Tripper is a full-service hotel web technology provider and strategic partner in helping hotels worldwide to optimize conversions, expand reach, and generate demand. We power properties with innovative technological solutions, including RezTrip, our industry leading central reservation system and hotel booking engine, and Travel Tripper Web, our fully integrated website and mobile platform.</p>
                    <a href="#services" class="page-scroll btn btn-default btn-xl">Get Started!</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">The "suite" solution from search to stay</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-8 text-center">
                    <div class="service-box">
                          <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>CRS & Distribution</h3>
                        <p class="text-muted">Travel Tripper CRS is your most powerful tool in managing room rates, inventory, and reservations. Our platform provides comprehensive hotel distribution to all major channels, seamless connectivity to the major PMS/RMS services, and robust tools for pricing and revenue management.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>Booking Engine</h3>
                        <p class="text-muted">Find out why hotels love RezTrip, Travel Tripper's innovative booking engine. With its sleek, user—friendly booking flow and unique features such as Automated Best Rate Guarantee, this booking engine is designed to optimize conversions through your most profitable channel—your website.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                        <h3>Up to Date</h3>
                        <p class="text-muted">Introducing Travel Tripper Web, a cloud web and booking platform designed specifically for hotels to entice travelers and drive direct bookings. Create stunning responsive websites perfect for web and mobile, and tap into intelligent features such as dynamic rate integration and interactive maps and calendars.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="/assets/1.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Hospital
                                </div>
                                <div class="project-name">
                                    Project1
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="/assets/2.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Ecommerce
                                </div>
                                <div class="project-name">
                                    Project2
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="/assets/3.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Business
                                </div>
                                <div class="project-name">
                                    Project 3
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="/assets/4.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Restaurant
                                </div>
                                <div class="project-name">
                                    Project 4
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="/assets/5.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Travel
                                </div>
                                <div class="project-name">
                                    Project 5
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="/assets/6.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Find out how Travel Tripper can help your hotel increase direct bookings and maximize revenue.</h2>
                <a href="#" class="btn btn-default btn-xl wow tada">REQUEST A DEMO</a>
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x wow bounceIn"></i>
                    <p>+44-02038085753</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto: hello@traveltripper.com">Say Hello →</a></p>
                </div>
            </div>
        </div>
    </section>

<%if user_signed_in? and !@page_design.nil?%>
<style type="text/css">
#mainNav{
  background: <%=@page_design.header_bg_color unless @page_design.header_bg_color.nil?%>;
}
#page-top{
background-color : <%=@page_design.body_bg_color%>;
font-family: <%=@page_design.page_font%>;
}
header,#about{
  background: <%=@page_design.about_bg_color%>;
}
#services{
   background-color: <%=@page_design.services_bg_color%>;
}
.bg-dark{
   background-color: <%=@page_design.portfolio_bg_color%>;
}
#contact{
   background-color: <%=@page_design.footer_bg_color%>;
}
</style>
<%end%>

app/views/layouts/_header.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">TravelTripper</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Services</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">Portfolio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <% if user_signed_in? %>
                    <li>
                      <%= link_to('Page Design',page_designs_path) %>        
                      </li>
                      <li>
                      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                      </li>
                    <% else %>
                      <li>
                      <%= link_to('Login', new_user_session_path)  %>  
                      </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= user_signed_in? ? "#{current_user.page_design.page_title}" : "TRAVEL TRIPPER" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
     
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body id="page-top">
  <%=render "layouts/header"%>
  <!-- <span class="notice"><%= notice %></span>
  <span class="alert"><%= alert %></span> -->
  <%=yield%>
  </body>
</html>

app/views/page_designs/_form.html.erb
<div style="text-align:center">
<%= form_for(@page_design) do |f| %>
  <% if @page_design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page_design.errors.count, "error") %> prohibited this page_design from being saved:</h2>

      <ul>
      <% @page_design.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
    <%= f.label :page_title %><br />
    <%= f.text_field :page_title%>
  </div>
  <div class="field">
    <%= f.label :font_family %><br />
    <%= f.text_field :page_font%>
  </div>
  <div class="field">
    <%= f.label :header_background_color %><br />
    <%= f.text_field :header_bg_color%>
  </div>

  <div class="field">
    <%= f.label :body_background_color %><br />
    <%= f.text_field :body_bg_color%>
  </div>

  <div class="field">
    <%= f.label :about_background_color %><br />
    <%= f.text_field :about_bg_color%>
  </div>

  <div class="field">
    <%= f.label :services_background_color %><br />
    <%= f.text_field :services_bg_color%>
  </div>

  <div class="field">
    <%= f.label :portfolio_background_color %><br />
    <%= f.text_field :portfolio_bg_color%>
  </div>

   <div class="field">
    <%= f.label :footer_backgroundg_color %><br />
    <%= f.text_field :footer_bg_color%>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>

<%end%>
<script type="text/javascript">
  $(document).ready(function(){
    $("#page_design_header_bg_color,#page_design_body_bg_color,#page_design_about_bg_color,#page_design_services_bg_color,#page_design_portfolio_bg_color,#page_design_footer_bg_color").colorpicker().on('changeColor', function(ev) {
      var color = ev.color.toHex();
    });
  });
</script>

app/views/page_designs/edit.html.erb
<div style="text-align:center;">
<h1>Editing Page Design</h1>

<%= render 'form' %>

<%= link_to 'Show', @page_design %> |
<%= link_to 'Back', page_designs_path %>
</div>

app/views/page_designs/index.html.erb
<div style="text-align:center;">
<p id="notice"><%= notice %></p>

<h1>Listing Page Designs</h1>
<%unless @page_design.nil?%>
  <table align="center">
    <thead>
      <tr>
        <th>Page Title</th>
        <th>Font Family</th>
        <th>Header Background color</th>
        <th>Body Background color</th>
        <th colspan="6"></th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= @page_design.page_title %></td>
          <td><%= @page_design.page_font %></td>
          <td><%= @page_design.header_bg_color %></td>
          <td><%= @page_design.body_bg_color %></td>
          <td><%= link_to 'Show', @page_design %>&nbsp;&nbsp;</td>
          <td><%= link_to 'Edit', edit_page_design_path(@page_design) %>&nbsp;</td>
          <td><%= link_to 'Destroy', @page_design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    </tbody>
  </table>
<%else%>
<p>Page design is not found </p>
<%end%>

<br>
<%if  @page_design.nil? %>
<%= link_to 'New Page design', new_page_design_path %>
<%end%>
</div>

app/views/page_designs/new.html.erb
<h1>New Page Design</h1>

<%= render 'form' %>

<%= link_to 'Back', page_designs_path %>

app/views/page_designs/show.html.erb
<div style="text-align:center;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Page Title:</strong>
  <%= @page_design.page_title %>
</p>
<p>
  <strong>Font Family:</strong>
  <%= @page_design.page_font %>
</p>
<p>
  <strong>Header Background color:</strong>
  <%= @page_design.header_bg_color %>
</p>
<p>
  <strong>Body Background color:</strong>
  <%= @page_design.body_bg_color %>
</p>
<p>
  <strong>About Background color:</strong>
  <%= @page_design.about_bg_color %>
</p>
<p>
  <strong>Services Background color:</strong>
  <%= @page_design.services_bg_color %>
</p>
<p>
  <strong>Portfolio Background color:</strong>
  <%= @page_design.portfolio_bg_color %>
</p>
<p>
  <strong>Footer Background color:</strong>
  <%= @page_design.footer_bg_color %>
</p>



<%= link_to 'Edit', edit_page_design_path(@page_design) %> |
<%= link_to 'Back', page_designs_path %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>